"""
mixpanel_data - Python library for working with Mixpanel analytics data.

Complete programmable interface to Mixpanel analytics: discover your schema,
run live analytics, stream data, and manage entities via the App API.
"""

from mixpanel_data._internal.validation import validate_bookmark
from mixpanel_data._literal_types import (
    ConversionWindowUnit,
    CountType,
    FilterDateUnit,
    FilterPropertyType,
    FiltersCombinator,
    FlowAnchorType,
    FlowChartType,
    FlowConversionWindowUnit,
    FlowCountType,
    FlowNodeType,
    FunnelMathType,
    FunnelMode,
    FunnelOrder,
    HourDayUnit,
    InsightsMode,
    MathType,
    PerUserAggregation,
    QueryTimeUnit,
    RetentionAlignment,
    RetentionMathType,
    RetentionMode,
    TimeUnit,
)
from mixpanel_data.exceptions import (
    AccountExistsError,
    AccountNotFoundError,
    APIError,
    AuthenticationError,
    BookmarkValidationError,
    ConfigError,
    DateRangeTooLargeError,
    EventNotFoundError,
    JQLSyntaxError,
    MixpanelDataError,
    OAuthError,
    QueryError,
    RateLimitError,
    ServerError,
    ValidationError,
    WorkspaceScopeError,
)
from mixpanel_data.types import (
    # Result types
    ActivityFeedResult,
    AlertBookmark,
    AlertCount,
    AlertCreator,
    AlertFrequencyPreset,
    AlertHistoryPagination,
    AlertHistoryResponse,
    AlertProject,
    AlertScreenshotResponse,
    AlertValidation,
    AlertWorkspace,
    # Operational Tooling types (Phase 026)
    Annotation,
    AnnotationTag,
    AnnotationUser,
    AuditResponse,
    AuditViolation,
    BlueprintCard,
    BlueprintConfig,
    BlueprintFinishParams,
    BlueprintTemplate,
    Bookmark,
    BookmarkHistoryPagination,
    BookmarkHistoryResponse,
    BookmarkInfo,
    BookmarkMetadata,
    BookmarkType,
    BulkAnomalyEntry,
    BulkCreateSchemasParams,
    BulkCreateSchemasResponse,
    # Data Governance types (Phase 027)
    BulkEventUpdate,
    BulkPatchResult,
    BulkPropertyUpdate,
    BulkUpdateAnomalyParams,
    BulkUpdateBookmarkEntry,
    BulkUpdateCohortEntry,
    BulkUpdateEventsParams,
    BulkUpdatePropertiesParams,
    Cohort,
    CohortBreakdown,
    CohortCreator,
    CohortCriteria,
    CohortDefinition,
    CohortInfo,
    CohortMetric,
    ComposedPropertyValue,
    CreateAlertParams,
    CreateAnnotationParams,
    CreateAnnotationTagParams,
    CreateBookmarkParams,
    CreateCohortParams,
    CreateCustomPropertyParams,
    CreateDashboardParams,
    CreateDeletionRequestParams,
    CreateDropFilterParams,
    CreateExperimentParams,
    CreateFeatureFlagParams,
    CreateRcaDashboardParams,
    CreateTagParams,
    CreateWebhookParams,
    CursorPagination,
    CustomAlert,
    CustomProperty,
    CustomPropertyRef,
    CustomPropertyResourceType,
    DailyCount,
    DailyCountsResult,
    Dashboard,
    DataVolumeAnomaly,
    DeleteSchemasResponse,
    DropFilter,
    DropFilterLimitsResponse,
    DuplicateExperimentParams,
    EngagementBucket,
    EngagementDistributionResult,
    EntityType,
    EventCountsResult,
    EventDefinition,
    EventDeletionRequest,
    Exclusion,
    Experiment,
    ExperimentConcludeParams,
    ExperimentCreator,
    ExperimentDecideParams,
    ExperimentStatus,
    FeatureFlag,
    FeatureFlagStatus,
    Filter,
    FlagContractStatus,
    FlagHistoryParams,
    FlagHistoryResponse,
    FlagLimitsResponse,
    # Result structure TypedDicts (Phase 038)
    FlowEdge,
    FlowQueryResult,
    FlowsResult,
    FlowStep,
    FlowStepNode,
    FlowTreeNode,
    Formula,
    FrequencyResult,
    FunnelInfo,
    FunnelQueryResult,
    FunnelResult,
    FunnelResultStep,
    FunnelStep,
    FunnelStepData,
    GroupBy,
    HoldingConstant,
    InitSchemaEnforcementParams,
    InlineCustomProperty,
    JQLResult,
    LexiconDefinition,
    LexiconMetadata,
    LexiconProperty,
    LexiconSchema,
    LexiconTag,
    LookupTable,
    LookupTableUploadUrl,
    MarkLookupTableReadyParams,
    Metric,
    NumericAverageResult,
    NumericBucketResult,
    NumericPropertySummaryResult,
    NumericSumResult,
    PaginatedResponse,
    PreviewDeletionFiltersParams,
    ProfilePageResult,
    ProjectWebhook,
    PropertyCountsResult,
    PropertyCoverage,
    PropertyCoverageResult,
    PropertyDefinition,
    PropertyDistributionResult,
    PropertyInput,
    PropertyResourceType,
    PropertySpec,
    PropertyValueCount,
    PublicWorkspace,
    QueryMeta,
    QueryResult,
    RcaSourceData,
    ReplaceSchemaEnforcementParams,
    RetentionCohortData,
    RetentionEvent,
    RetentionQueryResult,
    RetentionResult,
    SavedCohort,
    SavedReportResult,
    SavedReportType,
    SchemaEnforcementConfig,
    SchemaEntry,
    SegmentationResult,
    ServingMethod,
    SetTestUsersParams,
    TopEvent,
    UpdateAlertParams,
    UpdateAnnotationParams,
    UpdateAnomalyParams,
    UpdateBookmarkParams,
    UpdateCohortParams,
    UpdateCustomPropertyParams,
    UpdateDashboardParams,
    UpdateDropFilterParams,
    UpdateEventDefinitionParams,
    UpdateExperimentParams,
    UpdateFeatureFlagParams,
    UpdateLookupTableParams,
    UpdatePropertyDefinitionParams,
    UpdateReportLinkParams,
    UpdateSchemaEnforcementParams,
    UpdateTagParams,
    UpdateTextCardParams,
    UpdateWebhookParams,
    UploadLookupTableParams,
    UserEvent,
    ValidateAlertsForBookmarkParams,
    ValidateAlertsForBookmarkResponse,
    WebhookAuthType,
    WebhookMutationResult,
    WebhookTestParams,
    WebhookTestResult,
)
from mixpanel_data.workspace import Workspace

__version__ = "0.1.0"

__all__ = [
    # Core
    "Workspace",
    # Validation
    "validate_bookmark",
    # Type aliases — time units
    "TimeUnit",
    "HourDayUnit",
    "QueryTimeUnit",
    # Type aliases — count/math types
    "CountType",
    "MathType",
    "PerUserAggregation",
    # Type aliases — funnel types
    "FunnelMathType",
    "ConversionWindowUnit",
    "FunnelOrder",
    "FunnelMode",
    # Type aliases — retention types
    "RetentionAlignment",
    "RetentionMode",
    "RetentionMathType",
    # Type aliases — flow types
    "FlowCountType",
    "FlowChartType",
    "FlowConversionWindowUnit",
    "FlowNodeType",
    "FlowAnchorType",
    # Type aliases — insights
    "InsightsMode",
    # Type aliases — filter types
    "FilterPropertyType",
    "FilterDateUnit",
    "FiltersCombinator",
    # Result structure TypedDicts
    "QueryMeta",
    "FunnelStepData",
    "RetentionCohortData",
    "FlowStepNode",
    "FlowEdge",
    # Exceptions
    "MixpanelDataError",
    "BookmarkValidationError",
    "ValidationError",
    "APIError",
    "ConfigError",
    "AccountNotFoundError",
    "AccountExistsError",
    "AuthenticationError",
    "RateLimitError",
    "QueryError",
    "JQLSyntaxError",
    "ServerError",
    "EventNotFoundError",
    "DateRangeTooLargeError",
    "OAuthError",
    "WorkspaceScopeError",
    # Result types
    "SegmentationResult",
    "FunnelResult",
    "FunnelResultStep",
    "RetentionResult",
    "CohortInfo",
    "JQLResult",
    # Discovery types
    "FunnelInfo",
    "SavedCohort",
    "TopEvent",
    "EventCountsResult",
    "PropertyCountsResult",
    # Bookmark types (Phase 015)
    "BookmarkInfo",
    "BookmarkType",
    "SavedReportResult",
    "SavedReportType",
    "FlowsResult",
    # Phase 008: Query Service Enhancement types
    "UserEvent",
    "ActivityFeedResult",
    "FrequencyResult",
    "NumericBucketResult",
    "NumericSumResult",
    "NumericAverageResult",
    # Lexicon schema types
    "EntityType",
    "LexiconMetadata",
    "LexiconProperty",
    "LexiconDefinition",
    "LexiconSchema",
    # JQL Discovery types (Phase 016)
    "PropertyDistributionResult",
    "PropertyValueCount",
    "NumericPropertySummaryResult",
    "DailyCountsResult",
    "DailyCount",
    "EngagementDistributionResult",
    "EngagementBucket",
    "PropertyCoverageResult",
    "PropertyCoverage",
    # Profile pagination
    "ProfilePageResult",
    # App API types (Phase 023)
    "PublicWorkspace",
    "CursorPagination",
    "PaginatedResponse",
    # Core Entity CRUD types (Phase 024)
    "Dashboard",
    "CreateDashboardParams",
    "UpdateDashboardParams",
    "BlueprintTemplate",
    "BlueprintConfig",
    "BlueprintCard",
    "BlueprintFinishParams",
    "CreateRcaDashboardParams",
    "RcaSourceData",
    "UpdateReportLinkParams",
    "UpdateTextCardParams",
    "Bookmark",
    "BookmarkMetadata",
    "CreateBookmarkParams",
    "UpdateBookmarkParams",
    "BulkUpdateBookmarkEntry",
    "BookmarkHistoryResponse",
    "BookmarkHistoryPagination",
    # Cohort Definition Builder (Phase 035)
    "CohortCriteria",
    "CohortDefinition",
    # Cohort Behaviors (Phase 036)
    "CohortBreakdown",
    "CohortMetric",
    # Custom Property Query Types (Phase 037)
    "PropertyInput",
    "InlineCustomProperty",
    "CustomPropertyRef",
    "PropertySpec",
    # Cohort CRUD (Phase 024)
    "Cohort",
    "CohortCreator",
    "CreateCohortParams",
    "UpdateCohortParams",
    "BulkUpdateCohortEntry",
    # Feature Management types (Phase 025)
    "FeatureFlagStatus",
    "ServingMethod",
    "FlagContractStatus",
    "ExperimentStatus",
    "ExperimentCreator",
    "FeatureFlag",
    "CreateFeatureFlagParams",
    "UpdateFeatureFlagParams",
    "SetTestUsersParams",
    "FlagHistoryParams",
    "FlagHistoryResponse",
    "FlagLimitsResponse",
    "Experiment",
    "CreateExperimentParams",
    "UpdateExperimentParams",
    "ExperimentConcludeParams",
    "ExperimentDecideParams",
    "DuplicateExperimentParams",
    # Operational Tooling types (Phase 026)
    "Annotation",
    "AnnotationUser",
    "AnnotationTag",
    "CreateAnnotationParams",
    "UpdateAnnotationParams",
    "CreateAnnotationTagParams",
    "ProjectWebhook",
    "WebhookAuthType",
    "CreateWebhookParams",
    "UpdateWebhookParams",
    "WebhookTestParams",
    "WebhookTestResult",
    "WebhookMutationResult",
    "CustomAlert",
    "AlertBookmark",
    "AlertCreator",
    "AlertWorkspace",
    "AlertProject",
    "AlertFrequencyPreset",
    "CreateAlertParams",
    "UpdateAlertParams",
    "AlertCount",
    "AlertHistoryResponse",
    "AlertHistoryPagination",
    "AlertScreenshotResponse",
    "AlertValidation",
    "ValidateAlertsForBookmarkParams",
    "ValidateAlertsForBookmarkResponse",
    # Data Governance types (Phase 027)
    "PropertyResourceType",
    "CustomPropertyResourceType",
    "EventDefinition",
    "PropertyDefinition",
    "UpdateEventDefinitionParams",
    "UpdatePropertyDefinitionParams",
    "BulkEventUpdate",
    "BulkUpdateEventsParams",
    "BulkPropertyUpdate",
    "BulkUpdatePropertiesParams",
    "LexiconTag",
    "CreateTagParams",
    "UpdateTagParams",
    "DropFilter",
    "CreateDropFilterParams",
    "UpdateDropFilterParams",
    "DropFilterLimitsResponse",
    "ComposedPropertyValue",
    "CustomProperty",
    "CreateCustomPropertyParams",
    "UpdateCustomPropertyParams",
    "LookupTable",
    "UploadLookupTableParams",
    "MarkLookupTableReadyParams",
    "LookupTableUploadUrl",
    "UpdateLookupTableParams",
    # Query API types (Phase 029)
    "MathType",
    "PerUserAggregation",
    "Metric",
    "Filter",
    "Formula",
    "GroupBy",
    "FilterDateUnit",
    "FilterPropertyType",
    "QueryResult",
    # Schema Registry & Data Governance types (Phase 028)
    "SchemaEntry",
    "BulkCreateSchemasParams",
    "BulkCreateSchemasResponse",
    "BulkPatchResult",
    "DeleteSchemasResponse",
    "SchemaEnforcementConfig",
    "InitSchemaEnforcementParams",
    "UpdateSchemaEnforcementParams",
    "ReplaceSchemaEnforcementParams",
    "AuditResponse",
    "AuditViolation",
    "DataVolumeAnomaly",
    "UpdateAnomalyParams",
    "BulkUpdateAnomalyParams",
    "BulkAnomalyEntry",
    "EventDeletionRequest",
    "CreateDeletionRequestParams",
    "PreviewDeletionFiltersParams",
    # Funnel Query types (Phase 032)
    "FunnelStep",
    "Exclusion",
    "HoldingConstant",
    "FunnelMathType",
    "FunnelQueryResult",
    # Retention Query types (Phase 033)
    "RetentionAlignment",
    "RetentionEvent",
    "RetentionMathType",
    "RetentionMode",
    "RetentionQueryResult",
    # Flow Query types (Phase 034)
    "FlowStep",
    "FlowTreeNode",
    "FlowQueryResult",
]
