"""
mixpanel_data - Python library for working with Mixpanel analytics data.

Designed for AI coding agents. Fetch data once into a local DuckDB database,
then query it repeatedly with SQL.
"""

from mixpanel_data._literal_types import CountType, HourDayUnit, TableType, TimeUnit
from mixpanel_data.exceptions import (
    AccountExistsError,
    AccountNotFoundError,
    APIError,
    AuthenticationError,
    ConfigError,
    DatabaseLockedError,
    DatabaseNotFoundError,
    DateRangeTooLargeError,
    EventNotFoundError,
    JQLSyntaxError,
    MixpanelDataError,
    OAuthError,
    QueryError,
    RateLimitError,
    ServerError,
    TableExistsError,
    TableNotFoundError,
    WorkspaceScopeError,
)
from mixpanel_data.types import (
    ActivityFeedResult,
    BatchProgress,
    BatchResult,
    BlueprintCard,
    BlueprintConfig,
    BlueprintFinishParams,
    BlueprintTemplate,
    Bookmark,
    BookmarkHistoryPagination,
    BookmarkHistoryResponse,
    BookmarkInfo,
    BookmarkMetadata,
    BookmarkType,
    BulkUpdateBookmarkEntry,
    BulkUpdateCohortEntry,
    Cohort,
    CohortCreator,
    CohortInfo,
    ColumnInfo,
    ColumnStatsResult,
    ColumnSummary,
    CreateBookmarkParams,
    CreateCohortParams,
    CreateDashboardParams,
    CreateRcaDashboardParams,
    CursorPagination,
    DailyCount,
    DailyCountsResult,
    Dashboard,
    EngagementBucket,
    EngagementDistributionResult,
    EntityType,
    EventBreakdownResult,
    EventCountsResult,
    EventStats,
    FetchResult,
    FlowsResult,
    FrequencyResult,
    FunnelInfo,
    FunnelResult,
    FunnelStep,
    JQLResult,
    LexiconDefinition,
    LexiconMetadata,
    LexiconProperty,
    LexiconSchema,
    NumericAverageResult,
    NumericBucketResult,
    NumericPropertySummaryResult,
    NumericSumResult,
    PaginatedResponse,
    ParallelFetchResult,
    ParallelProfileResult,
    ProfilePageResult,
    ProfileProgress,
    PropertyCountsResult,
    PropertyCoverage,
    PropertyCoverageResult,
    PropertyDistributionResult,
    PropertyValueCount,
    PublicWorkspace,
    RcaSourceData,
    RetentionResult,
    SavedCohort,
    SavedReportResult,
    SavedReportType,
    SegmentationResult,
    SQLResult,
    SummaryResult,
    TableInfo,
    TableMetadata,
    TableSchema,
    TopEvent,
    UpdateBookmarkParams,
    UpdateCohortParams,
    UpdateDashboardParams,
    UpdateReportLinkParams,
    UpdateTextCardParams,
    UserEvent,
    WorkspaceInfo,
)
from mixpanel_data.workspace import Workspace

__version__ = "0.1.0"

__all__ = [
    # Core
    "Workspace",
    # Type aliases
    "CountType",
    "HourDayUnit",
    "TableType",
    "TimeUnit",
    # Exceptions
    "MixpanelDataError",
    "APIError",
    "ConfigError",
    "AccountNotFoundError",
    "AccountExistsError",
    "AuthenticationError",
    "RateLimitError",
    "QueryError",
    "JQLSyntaxError",
    "ServerError",
    "TableExistsError",
    "TableNotFoundError",
    "DatabaseLockedError",
    "DatabaseNotFoundError",
    "EventNotFoundError",
    "DateRangeTooLargeError",
    "OAuthError",
    "WorkspaceScopeError",
    # Result types
    "FetchResult",
    "ParallelFetchResult",
    "ParallelProfileResult",
    "ProfilePageResult",
    "BatchProgress",
    "BatchResult",
    "ProfileProgress",
    "SegmentationResult",
    "SQLResult",
    "FunnelResult",
    "FunnelStep",
    "RetentionResult",
    "CohortInfo",
    "JQLResult",
    # Discovery types
    "FunnelInfo",
    "SavedCohort",
    "TopEvent",
    "EventCountsResult",
    "PropertyCountsResult",
    # Bookmark types (Phase 015)
    "BookmarkInfo",
    "BookmarkType",
    "SavedReportResult",
    "SavedReportType",
    "FlowsResult",
    # Phase 008: Query Service Enhancement types
    "UserEvent",
    "ActivityFeedResult",
    "FrequencyResult",
    "NumericBucketResult",
    "NumericSumResult",
    "NumericAverageResult",
    # Storage types
    "TableMetadata",
    "TableInfo",
    "ColumnInfo",
    "TableSchema",
    # Workspace types
    "WorkspaceInfo",
    # Lexicon schema types
    "EntityType",
    "LexiconMetadata",
    "LexiconProperty",
    "LexiconDefinition",
    "LexiconSchema",
    # Introspection types
    "ColumnSummary",
    "SummaryResult",
    "EventStats",
    "EventBreakdownResult",
    "ColumnStatsResult",
    # JQL Discovery types (Phase 016)
    "PropertyDistributionResult",
    "PropertyValueCount",
    "NumericPropertySummaryResult",
    "DailyCountsResult",
    "DailyCount",
    "EngagementDistributionResult",
    "EngagementBucket",
    "PropertyCoverageResult",
    "PropertyCoverage",
    # App API types (Phase 023)
    "PublicWorkspace",
    "CursorPagination",
    "PaginatedResponse",
    # Core Entity CRUD types (Phase 024)
    "Dashboard",
    "CreateDashboardParams",
    "UpdateDashboardParams",
    "BlueprintTemplate",
    "BlueprintConfig",
    "BlueprintCard",
    "BlueprintFinishParams",
    "CreateRcaDashboardParams",
    "RcaSourceData",
    "UpdateReportLinkParams",
    "UpdateTextCardParams",
    "Bookmark",
    "BookmarkMetadata",
    "CreateBookmarkParams",
    "UpdateBookmarkParams",
    "BulkUpdateBookmarkEntry",
    "BookmarkHistoryResponse",
    "BookmarkHistoryPagination",
    "Cohort",
    "CohortCreator",
    "CreateCohortParams",
    "UpdateCohortParams",
    "BulkUpdateCohortEntry",
]
