"""Shared types for MCP Server v2 intelligent tools, middleware, and resources.

This module defines the data structures used by intelligent tools (Tier 3),
composed tools (Tier 2), interactive tools, and middleware components.

All types are defined as dataclasses for MCP protocol compatibility.
"""

from dataclasses import dataclass, field
from typing import Any, Literal

# ==============================================================================
# Core Result Types
# ==============================================================================


@dataclass
class AnalysisResult:
    """Result from an intelligent tool with AI synthesis.

    Intelligent tools (Tier 3) use sampling for synthesis but gracefully degrade
    to raw data when sampling is unavailable.

    Attributes:
        status: Execution status indicating whether synthesis was performed.
        findings: AI-synthesized findings when sampling is available.
        recommendations: Actionable recommendations derived from analysis.
        confidence: Confidence level in the analysis.
        raw_data: Underlying query results for transparency.
        analysis_hints: Manual analysis hints when sampling unavailable.

    Example:
        ```python
        result = AnalysisResult(
            status="success",
            findings={"key_insight": "Mobile users dropped 25%"},
            recommendations=["Investigate iOS crash reports"],
            confidence="high",
            raw_data={"baseline": 1000, "current": 750},
        )
        ```
    """

    status: Literal["success", "partial", "sampling_unavailable"]
    """Execution status: success (full synthesis), partial (some queries failed),
    or sampling_unavailable (client doesn't support sampling)."""

    findings: dict[str, Any] | None = None
    """AI-synthesized findings when sampling is available."""

    recommendations: list[str] = field(default_factory=list)
    """Actionable recommendations derived from analysis."""

    confidence: Literal["low", "medium", "high"] | None = None
    """Confidence level in the analysis."""

    raw_data: dict[str, Any] = field(default_factory=dict)
    """Underlying query results for transparency."""

    analysis_hints: list[str] = field(default_factory=list)
    """Manual analysis hints when sampling unavailable."""


# ==============================================================================
# Execution Plan Types (for ask_mixpanel)
# ==============================================================================


@dataclass
class QuerySpec:
    """Specification for a single query to execute.

    Used by ExecutionPlan to describe individual queries that answer
    a natural language question.

    Attributes:
        method: The Workspace method to call.
        params: Parameters to pass to the method.

    Example:
        ```python
        query = QuerySpec(
            method="segmentation",
            params={"event": "login", "from_date": "2026-01-01"},
        )
        ```
    """

    method: Literal[
        "segmentation",
        "retention",
        "funnel",
        "property_counts",
        "event_counts",
        "activity_feed",
        "jql",
    ]
    """The Workspace method to call."""

    params: dict[str, Any] = field(default_factory=dict)
    """Parameters to pass to the method."""


@dataclass
class ExecutionPlan:
    """Plan for answering a natural language question.

    Generated by ask_mixpanel to translate natural language queries
    into executable Workspace method calls.

    Attributes:
        intent: Brief description of user's analytical intent.
        query_type: Primary analysis type (retention, conversion, trend, etc.).
        queries: List of queries to execute.
        date_range: Date range for all queries.
        comparison_needed: Whether comparison between periods/segments is required.
        reasoning: Explanation of why these queries answer the question.

    Example:
        ```python
        plan = ExecutionPlan(
            intent="Analyze user retention after signup",
            query_type="retention",
            queries=[QuerySpec(method="retention", params={...})],
            date_range={"from_date": "2026-01-01", "to_date": "2026-01-31"},
            comparison_needed=False,
            reasoning="Retention analysis shows return rate after signup",
        )
        ```
    """

    intent: str
    """Brief description of user's analytical intent."""

    query_type: str
    """Primary analysis type (retention, conversion, trend, etc.)."""

    queries: list[QuerySpec]
    """List of queries to execute."""

    date_range: dict[str, str]
    """Date range for all queries: {from_date, to_date}."""

    comparison_needed: bool = False
    """Whether comparison between periods/segments is required."""

    reasoning: str = ""
    """Explanation of why these queries answer the question."""


# ==============================================================================
# Diagnosis Types (for diagnose_metric_drop)
# ==============================================================================


@dataclass
class SegmentContribution:
    """A segment's contribution to a metric change.

    Used by DiagnosisResult to describe which segments are driving
    a metric drop or increase.

    Attributes:
        dimension: Property dimension (e.g., 'platform', 'country').
        segment: Specific segment value (e.g., 'iOS', 'US').
        contribution_pct: Percentage of total drop attributable to this segment.
        baseline_value: Value during baseline period.
        current_value: Value during drop period.
        description: Human-readable description of the impact.

    Example:
        ```python
        contribution = SegmentContribution(
            dimension="platform",
            segment="iOS",
            contribution_pct=65.0,
            baseline_value=1000,
            current_value=650,
            description="iOS users dropped by 35%, accounting for 65% of total drop",
        )
        ```
    """

    dimension: str
    """Property dimension (e.g., 'platform', 'country')."""

    segment: str
    """Specific segment value (e.g., 'iOS', 'US')."""

    contribution_pct: float
    """Percentage of total drop attributable to this segment."""

    baseline_value: float
    """Value during baseline period."""

    current_value: float
    """Value during drop period."""

    description: str
    """Human-readable description of the impact."""


@dataclass
class DiagnosisResult:
    """Result from diagnose_metric_drop tool.

    Provides structured analysis of a metric drop including primary driver,
    secondary factors, and recommendations.

    Attributes:
        drop_confirmed: Whether a significant drop was detected.
        drop_percentage: Percentage change from baseline to drop period.
        primary_driver: Main segment contributing to the drop.
        secondary_factors: Other contributing segments.
        recommendations: Actionable next steps.
        confidence: Confidence in the diagnosis.
        caveats: Data quality concerns or limitations.
        raw_data: Underlying query results.

    Example:
        ```python
        result = DiagnosisResult(
            drop_confirmed=True,
            drop_percentage=-25.0,
            primary_driver=SegmentContribution(...),
            recommendations=["Check iOS app store reviews"],
            confidence="high",
        )
        ```
    """

    drop_confirmed: bool
    """Whether a significant drop was detected."""

    drop_percentage: float
    """Percentage change from baseline to drop period."""

    primary_driver: SegmentContribution | None = None
    """Main segment contributing to the drop."""

    secondary_factors: list[SegmentContribution] = field(default_factory=list)
    """Other contributing segments."""

    recommendations: list[str] = field(default_factory=list)
    """Actionable next steps."""

    confidence: Literal["low", "medium", "high"] = "medium"
    """Confidence in the diagnosis."""

    caveats: list[str] = field(default_factory=list)
    """Data quality concerns or limitations."""

    raw_data: dict[str, Any] = field(default_factory=dict)
    """Underlying query results."""


# ==============================================================================
# Funnel Optimization Types
# ==============================================================================


@dataclass
class OptimizationRecommendation:
    """A single optimization recommendation.

    Used by FunnelOptimizationResult to provide actionable advice.

    Attributes:
        action: What to do.
        priority: Priority level.
        expected_impact: Expected improvement if implemented.

    Example:
        ```python
        rec = OptimizationRecommendation(
            action="Add progress indicator on checkout step",
            priority="high",
            expected_impact="Could improve step 3 conversion by 10-15%",
        )
        ```
    """

    action: str
    """What to do."""

    priority: Literal["high", "medium", "low"]
    """Priority level."""

    expected_impact: str
    """Expected improvement if implemented."""


@dataclass
class FunnelOptimizationResult:
    """Result from funnel_optimization_report tool.

    Provides comprehensive funnel analysis with bottleneck identification
    and optimization recommendations.

    Attributes:
        executive_summary: 2-3 sentence summary of key findings.
        overall_conversion_rate: End-to-end conversion rate.
        bottleneck: Details of worst-performing step.
        top_performing_segments: Segments with highest conversion.
        underperforming_segments: Segments with lowest conversion.
        recommendations: Prioritized optimization actions.
        raw_data: Underlying funnel and segment data.

    Example:
        ```python
        result = FunnelOptimizationResult(
            executive_summary="Checkout funnel converts at 12%. Step 3 is bottleneck.",
            overall_conversion_rate=0.12,
            bottleneck={"step_number": 3, "step_name": "Payment", "drop_pct": 45},
            recommendations=[OptimizationRecommendation(...)],
        )
        ```
    """

    executive_summary: str
    """2-3 sentence summary of key findings."""

    overall_conversion_rate: float
    """End-to-end conversion rate."""

    bottleneck: dict[str, Any]
    """Details of worst-performing step: {step_number, step_name, drop_percentage}."""

    top_performing_segments: list[dict[str, Any]] = field(default_factory=list)
    """Segments with highest conversion."""

    underperforming_segments: list[dict[str, Any]] = field(default_factory=list)
    """Segments with lowest conversion."""

    recommendations: list[OptimizationRecommendation] = field(default_factory=list)
    """Prioritized optimization actions."""

    raw_data: dict[str, Any] = field(default_factory=dict)
    """Underlying funnel and segment data."""


# ==============================================================================
# Dashboard Types
# ==============================================================================


@dataclass
class AARRRMetrics:
    """Metrics for one AARRR category.

    Used by ProductHealthDashboard to represent metrics for each
    pirate metrics category.

    Attributes:
        category: AARRR category.
        primary_metric: Main metric value for this category.
        trend: Time series data as {date: value}.
        by_segment: Breakdown by segment if available.

    Example:
        ```python
        metrics = AARRRMetrics(
            category="retention",
            primary_metric=0.35,
            trend={"2026-01-01": 0.32, "2026-01-08": 0.35},
        )
        ```
    """

    category: Literal["acquisition", "activation", "retention", "revenue", "referral"]
    """AARRR category."""

    primary_metric: float
    """Main metric value for this category."""

    trend: dict[str, float] = field(default_factory=dict)
    """Time series data: {date: value}."""

    by_segment: dict[str, dict[str, Any]] | None = None
    """Breakdown by segment if available."""


@dataclass
class ProductHealthDashboard:
    """Complete AARRR product health dashboard.

    Result from product_health_dashboard tool providing comprehensive
    pirate metrics analysis.

    Attributes:
        period: Analysis period as {from_date, to_date}.
        acquisition: Acquisition metrics (signups, traffic).
        activation: Activation metrics (onboarding, first value).
        retention: Retention metrics (D1/D7/D30 return rates).
        revenue: Revenue metrics (transactions, ARPU).
        referral: Referral metrics (invites, viral coefficient).
        health_score: Score 1-10 for each category.

    Example:
        ```python
        dashboard = ProductHealthDashboard(
            period={"from_date": "2026-01-01", "to_date": "2026-01-31"},
            acquisition=AARRRMetrics(category="acquisition", primary_metric=1000),
            retention=AARRRMetrics(category="retention", primary_metric=0.35),
            health_score={"acquisition": 8, "retention": 6},
        )
        ```
    """

    period: dict[str, str]
    """Analysis period: {from_date, to_date}."""

    acquisition: AARRRMetrics | None = None
    """Acquisition metrics (signups, traffic)."""

    activation: AARRRMetrics | None = None
    """Activation metrics (onboarding, first value)."""

    retention: AARRRMetrics | None = None
    """Retention metrics (D1/D7/D30 return rates)."""

    revenue: AARRRMetrics | None = None
    """Revenue metrics (transactions, ARPU)."""

    referral: AARRRMetrics | None = None
    """Referral metrics (invites, viral coefficient)."""

    health_score: dict[str, int] | None = None
    """Score 1-10 for each category."""


# ==============================================================================
# Investigation Types
# ==============================================================================


@dataclass
class QuestionFinding:
    """Finding for a single GQM question.

    Used by GQMInvestigation to report results for each sub-question.

    Attributes:
        question: The operational question.
        query_type: Type of query used.
        status: Whether query succeeded.
        result: Query result if successful.
        error: Error message if failed.

    Example:
        ```python
        finding = QuestionFinding(
            question="What is the day-7 retention rate?",
            query_type="retention",
            status="success",
            result={"d7_retention": 0.35},
        )
        ```
    """

    question: str
    """The operational question."""

    query_type: str
    """Type of query used."""

    status: Literal["success", "failed"]
    """Whether query succeeded."""

    result: dict[str, Any] | None = None
    """Query result if successful."""

    error: str | None = None
    """Error message if failed."""


@dataclass
class GQMInvestigation:
    """Result from gqm_investigation tool.

    Provides structured investigation using Goal-Question-Metric methodology.

    Attributes:
        interpreted_goal: Clarified version of user's goal.
        aarrr_category: Classification for scoping.
        period: Analysis period.
        schema_context: Available events and funnels used.
        questions: List of sub-questions generated.
        findings: Results for each question.
        synthesis: Overall synthesis of findings.
        next_steps: Suggested follow-up investigations.

    Example:
        ```python
        investigation = GQMInvestigation(
            interpreted_goal="Understand why retention is declining",
            aarrr_category="retention",
            period={"from_date": "2026-01-01", "to_date": "2026-01-31"},
            questions=[{"question": "What is current D7 retention?", ...}],
            findings=[QuestionFinding(...)],
            synthesis={"key_insight": "Retention dropped after v2.0 release"},
            next_steps=["Investigate v2.0 release impact"],
        )
        ```
    """

    interpreted_goal: str
    """Clarified version of user's goal."""

    aarrr_category: Literal[
        "acquisition", "activation", "retention", "revenue", "referral"
    ]
    """Classification for scoping."""

    period: dict[str, str]
    """Analysis period: {from_date, to_date}."""

    schema_context: dict[str, Any] = field(default_factory=dict)
    """Available events and funnels used."""

    questions: list[dict[str, str]] = field(default_factory=list)
    """List of sub-questions generated."""

    findings: list[QuestionFinding] = field(default_factory=list)
    """Results for each question."""

    synthesis: dict[str, Any] = field(default_factory=dict)
    """Overall synthesis of findings."""

    next_steps: list[str] = field(default_factory=list)
    """Suggested follow-up investigations."""


# ==============================================================================
# Cohort Comparison Types
# ==============================================================================


@dataclass
class CohortMetrics:
    """Metrics for a single cohort.

    Used by CohortComparison to represent one of the cohorts being compared.

    Attributes:
        name: Cohort display name.
        filter: Filter expression defining the cohort.
        user_count: Number of users in cohort.
        metrics: Computed metrics for this cohort.

    Example:
        ```python
        cohort = CohortMetrics(
            name="Power Users",
            filter='properties["sessions"] >= 10',
            user_count=5000,
            metrics={"retention_d7": 0.65, "events_per_user": 25},
        )
        ```
    """

    name: str
    """Cohort display name."""

    filter: str
    """Filter expression defining the cohort."""

    user_count: int | None = None
    """Number of users in cohort."""

    metrics: dict[str, Any] = field(default_factory=dict)
    """Computed metrics for this cohort."""


@dataclass
class CohortComparison:
    """Result from cohort_comparison tool.

    Provides comparative analysis of two user cohorts across behavioral dimensions.

    Attributes:
        cohort_a: First cohort.
        cohort_b: Second cohort.
        period: Analysis period.
        comparisons: Comparison results by dimension.
        statistical_significance: Whether differences are statistically significant.

    Example:
        ```python
        comparison = CohortComparison(
            cohort_a=CohortMetrics(name="Power Users", ...),
            cohort_b=CohortMetrics(name="Casual Users", ...),
            period={"from_date": "2026-01-01", "to_date": "2026-01-31"},
            comparisons={"retention": {...}, "event_frequency": {...}},
        )
        ```
    """

    cohort_a: CohortMetrics
    """First cohort."""

    cohort_b: CohortMetrics
    """Second cohort."""

    period: dict[str, str]
    """Analysis period."""

    comparisons: dict[str, dict[str, Any]] = field(default_factory=dict)
    """Comparison results by dimension (retention, event_frequency, top_events)."""

    statistical_significance: dict[str, bool] | None = None
    """Whether differences are statistically significant."""


# ==============================================================================
# Elicitation Types
# ==============================================================================


@dataclass
class FetchConfirmation:
    """User confirmation for large fetch operation.

    Response type for safe_large_fetch elicitation.

    Attributes:
        proceed: Whether to proceed with the fetch.
        reduce_scope: Whether to reduce the scope.
        new_limit: New event limit if reducing scope.

    Example:
        ```python
        confirmation = FetchConfirmation(
            proceed=True,
            reduce_scope=True,
            new_limit=50000,
        )
        ```
    """

    proceed: bool
    """Whether to proceed with the fetch."""

    reduce_scope: bool = False
    """Whether to reduce the scope."""

    new_limit: int | None = None
    """New event limit if reducing scope."""


@dataclass
class AnalysisChoice:
    """User's choice for analysis direction.

    Response type for guided_analysis focus selection.

    Attributes:
        focus_area: Primary focus area.
        time_period: Analysis time period.
        custom_start: Custom start date if time_period is 'custom'.
        custom_end: Custom end date if time_period is 'custom'.

    Example:
        ```python
        choice = AnalysisChoice(
            focus_area="retention",
            time_period="last_30_days",
        )
        ```
    """

    focus_area: Literal["conversion", "retention", "engagement", "revenue"]
    """Primary focus area."""

    time_period: Literal["last_7_days", "last_30_days", "last_90_days", "custom"]
    """Analysis time period."""

    custom_start: str | None = None
    """Custom start date if time_period is 'custom'."""

    custom_end: str | None = None
    """Custom end date if time_period is 'custom'."""


@dataclass
class SegmentChoice:
    """User's choice for segment investigation.

    Response type for guided_analysis segment selection.

    Attributes:
        segment_index: Index of selected segment from presented list.
        investigate_further: Whether to drill deeper into this segment.

    Example:
        ```python
        choice = SegmentChoice(
            segment_index=2,
            investigate_further=True,
        )
        ```
    """

    segment_index: int
    """Index of selected segment from presented list."""

    investigate_further: bool = True
    """Whether to drill deeper into this segment."""


# ==============================================================================
# Middleware Types
# ==============================================================================


@dataclass
class RateLimitState:
    """State tracking for rate limiting.

    Internal state for managing rate limiting middleware.

    Attributes:
        request_times: Timestamps of recent requests.
        active_count: Number of currently active requests.

    Example:
        ```python
        state = RateLimitState(
            request_times=[1704067200.0, 1704067201.0],
            active_count=2,
        )
        ```
    """

    request_times: list[float] = field(default_factory=list)
    """Timestamps of recent requests."""

    active_count: int = 0
    """Number of currently active requests."""


@dataclass
class MixpanelRateLimits:
    """Mixpanel API rate limit configuration.

    Configuration for different Mixpanel API rate limits.

    Attributes:
        query_hourly_limit: Query API hourly limit.
        query_concurrent_limit: Query API concurrent request limit.
        export_hourly_limit: Export API hourly limit.
        export_per_second_limit: Export API per-second limit.
        export_concurrent_limit: Export API concurrent request limit.

    Example:
        ```python
        limits = MixpanelRateLimits(
            query_hourly_limit=60,
            query_concurrent_limit=5,
        )
        ```
    """

    query_hourly_limit: int = 60
    """Query API hourly limit."""

    query_concurrent_limit: int = 5
    """Query API concurrent request limit."""

    export_hourly_limit: int = 60
    """Export API hourly limit."""

    export_per_second_limit: int = 3
    """Export API per-second limit."""

    export_concurrent_limit: int = 100
    """Export API concurrent request limit."""


@dataclass
class CacheEntry:
    """Cached response entry.

    Internal structure for storing cached tool responses.

    Attributes:
        key: Cache key (hash of tool name + arguments).
        value: Cached result.
        created_at: Timestamp when cached.
        ttl: Time-to-live in seconds.

    Example:
        ```python
        entry = CacheEntry(
            key="list_events:abc123",
            value=["login", "signup", "purchase"],
            created_at=1704067200.0,
            ttl=300,
        )
        assert not entry.is_expired
        ```
    """

    key: str
    """Cache key (hash of tool name + arguments)."""

    value: Any
    """Cached result."""

    created_at: float
    """Timestamp when cached."""

    ttl: int
    """Time-to-live in seconds."""

    @property
    def is_expired(self) -> bool:
        """Check if cache entry has expired.

        Returns:
            True if the entry has exceeded its TTL, False otherwise.
        """
        import time

        return time.time() - self.created_at > self.ttl


# ==============================================================================
# Workflow Types (Operational Analytics Loop)
# ==============================================================================


@dataclass
class DateRange:
    """Date range for analytics queries.

    Attributes:
        from_date: Start date in YYYY-MM-DD format.
        to_date: End date in YYYY-MM-DD format.

    Example:
        ```python
        range = DateRange(from_date="2025-01-01", to_date="2025-01-31")
        ```
    """

    from_date: str
    """Start date in YYYY-MM-DD format."""

    to_date: str
    """End date in YYYY-MM-DD format."""


@dataclass
class Metric:
    """A single metric with current and comparison values.

    Attributes:
        name: Metric identifier (e.g., "signups", "d7_retention").
        display_name: Human-readable name.
        current: Current period value.
        previous: Comparison period value.
        change_percent: Percentage change from previous.
        trend: Direction indicator.
        unit: Metric unit (e.g., "count", "percent", "currency").

    Example:
        ```python
        metric = Metric(
            name="signups",
            display_name="Signups",
            current=12450.0,
            previous=14200.0,
            change_percent=-12.3,
            trend="down",
        )
        ```
    """

    name: str
    """Metric identifier (e.g., "signups", "d7_retention")."""

    display_name: str
    """Human-readable name."""

    current: float
    """Current period value."""

    previous: float
    """Comparison period value."""

    change_percent: float
    """Percentage change from previous."""

    trend: Literal["up", "down", "flat"]
    """Direction indicator."""

    unit: str = "count"
    """Metric unit (e.g., "count", "percent", "currency")."""


@dataclass
class DataPoint:
    """Single data point for time series.

    Attributes:
        date: Date in YYYY-MM-DD format.
        value: Numeric value for that date.

    Example:
        ```python
        point = DataPoint(date="2025-01-15", value=1234.5)
        ```
    """

    date: str
    """Date in YYYY-MM-DD format."""

    value: float
    """Numeric value for that date."""


@dataclass
class EventsSummary:
    """Summary of tracked events.

    Attributes:
        total: Total number of distinct events.
        top_events: List of most active event names.
        categories: Event counts by category (if categorized).

    Example:
        ```python
        summary = EventsSummary(
            total=47,
            top_events=["signup", "login", "purchase"],
            categories={"acquisition": 5, "activation": 8},
        )
        ```
    """

    total: int
    """Total number of distinct events."""

    top_events: list[str]
    """List of most active event names."""

    categories: dict[str, int] = field(default_factory=dict)
    """Event counts by category (if categorized)."""


@dataclass
class PropertiesSummary:
    """Summary of event and user properties.

    Attributes:
        event_properties: Count of event properties.
        user_properties: Count of user/profile properties.
        common: Properties that appear across multiple events.

    Example:
        ```python
        summary = PropertiesSummary(
            event_properties=120,
            user_properties=45,
            common=["platform", "country", "user_id"],
        )
        ```
    """

    event_properties: int
    """Count of event properties."""

    user_properties: int
    """Count of user/profile properties."""

    common: list[str] = field(default_factory=list)
    """Properties that appear across multiple events."""


@dataclass
class FunnelSummary:
    """Summary of a saved funnel.

    Attributes:
        id: Funnel ID in Mixpanel.
        name: Funnel name.
        steps: Number of steps in the funnel.

    Example:
        ```python
        summary = FunnelSummary(id=1, name="Signup Flow", steps=4)
        ```
    """

    id: int
    """Funnel ID in Mixpanel."""

    name: str
    """Funnel name."""

    steps: int
    """Number of steps in the funnel."""


@dataclass
class CohortSummary:
    """Summary of a saved cohort.

    Attributes:
        id: Cohort ID in Mixpanel.
        name: Cohort name.
        count: Approximate user count.

    Example:
        ```python
        summary = CohortSummary(id=101, name="Power Users", count=15000)
        ```
    """

    id: int
    """Cohort ID in Mixpanel."""

    name: str
    """Cohort name."""

    count: int
    """Approximate user count."""


@dataclass
class BookmarksSummary:
    """Summary of saved reports/bookmarks.

    Attributes:
        total: Total number of saved reports.
        by_type: Counts by report type (insight, board, etc.).

    Example:
        ```python
        summary = BookmarksSummary(
            total=12,
            by_type={"insight": 8, "board": 4},
        )
        ```
    """

    total: int
    """Total number of saved reports."""

    by_type: dict[str, int] = field(default_factory=dict)
    """Counts by report type (insight, board, etc.)."""


@dataclass
class ContextPackage:
    """Complete project context for analytics workflow.

    Aggregates project metadata, available events, funnels, cohorts,
    and bookmarks to provide foundation for subsequent analysis.

    Attributes:
        project: Project metadata (id, name, region).
        events: Summary of tracked events.
        properties: Summary of available properties.
        funnels: List of saved funnel summaries.
        cohorts: List of saved cohort summaries.
        bookmarks: Summary of saved reports.
        date_range: Available data date range.
        schemas: Optional Lexicon schema definitions.

    Example:
        ```python
        context = ContextPackage(
            project={"id": "123456", "name": "MyApp", "region": "us"},
            events=EventsSummary(total=47, top_events=["signup", "login"]),
            properties=PropertiesSummary(event_properties=120, user_properties=45),
            funnels=[FunnelSummary(id=1, name="Signup Flow", steps=4)],
            cohorts=[CohortSummary(id=101, name="Power Users", count=15000)],
            bookmarks=BookmarksSummary(total=12, by_type={"insight": 8}),
            date_range=DateRange(from_date="2024-01-01", to_date="2025-01-24"),
        )
        ```
    """

    project: dict[str, Any]
    """Project metadata (id, name, region)."""

    events: EventsSummary
    """Summary of tracked events."""

    properties: PropertiesSummary
    """Summary of available properties."""

    funnels: list[FunnelSummary]
    """List of saved funnel summaries."""

    cohorts: list[CohortSummary]
    """List of saved cohort summaries."""

    bookmarks: BookmarksSummary
    """Summary of saved reports."""

    date_range: DateRange
    """Available data date range."""

    schemas: list[dict[str, Any]] | None = None
    """Optional Lexicon schema definitions."""


@dataclass
class HealthDashboard:
    """Product health metrics dashboard with period comparison.

    Provides current KPIs, comparison to baseline period,
    and quick insights for monitoring product health.

    Attributes:
        period: Current analysis period.
        comparison_period: Baseline period for comparison.
        metrics: List of key metrics with current/previous values.
        aarrr: Optional AARRR framework breakdown.
        highlights: List of positive observations.
        concerns: List of concerning observations.
        daily_series: Time series data by metric name.

    Example:
        ```python
        dashboard = HealthDashboard(
            period=DateRange("2025-01-01", "2025-01-24"),
            comparison_period=DateRange("2024-12-01", "2024-12-24"),
            metrics=[
                Metric("signups", "Signups", 12450, 14200, -12.3, "down"),
            ],
            highlights=["Activation rate improved 2pp"],
            concerns=["Signups down 12%"],
        )
        ```
    """

    period: DateRange
    """Current analysis period."""

    comparison_period: DateRange
    """Baseline period for comparison."""

    metrics: list[Metric]
    """List of key metrics with current/previous values."""

    aarrr: dict[str, Any] | None = None
    """Optional AARRR framework breakdown."""

    highlights: list[str] = field(default_factory=list)
    """List of positive observations."""

    concerns: list[str] = field(default_factory=list)
    """List of concerning observations."""

    daily_series: dict[str, list[DataPoint]] = field(default_factory=dict)
    """Time series data by metric name."""


@dataclass
class Anomaly:
    """Detected anomaly or signal for investigation.

    Represents a statistical anomaly detected during scan,
    with unique ID for reference in investigate tool.

    Attributes:
        id: Unique identifier for this anomaly (deterministic).
        type: Type of anomaly detected.
        severity: Severity level based on magnitude and impact.
        category: AARRR category or custom category.
        summary: Human-readable description.
        event: Primary event involved.
        dimension: Property name if segment-specific.
        dimension_value: Property value if segment-specific.
        detected_at: Date when anomaly was detected.
        magnitude: Size of change (absolute or percentage).
        confidence: Statistical confidence (0.0 to 1.0).
        context: Additional context for investigation.

    Example:
        ```python
        anomaly = Anomaly(
            id="signup_drop_2025-01-15_a3f2b1c9",
            type="drop",
            severity="high",
            category="acquisition",
            summary="Signup conversion dropped 23% on Jan 15",
            event="signup",
            detected_at="2025-01-15",
            magnitude=23.0,
            confidence=0.92,
        )
        ```
    """

    id: str
    """Unique identifier for this anomaly (deterministic)."""

    type: Literal["drop", "spike", "trend_change", "segment_shift"]
    """Type of anomaly detected."""

    severity: Literal["critical", "high", "medium", "low"]
    """Severity level based on magnitude and impact."""

    category: str
    """AARRR category or custom category."""

    summary: str
    """Human-readable description."""

    event: str
    """Primary event involved."""

    dimension: str | None = None
    """Property name if segment-specific."""

    dimension_value: str | None = None
    """Property value if segment-specific."""

    detected_at: str = ""
    """Date when anomaly was detected."""

    magnitude: float = 0.0
    """Size of change (absolute or percentage)."""

    confidence: float = 0.0
    """Statistical confidence (0.0 to 1.0)."""

    context: dict[str, Any] = field(default_factory=dict)
    """Additional context for investigation."""


@dataclass
class ScanResults:
    """Results from anomaly detection scan.

    Contains ranked list of detected anomalies and metadata
    about what was analyzed.

    Attributes:
        period: Date range that was scanned.
        anomalies: List of detected anomalies, ranked by severity * confidence.
        scan_coverage: What events/dimensions were analyzed.
        baseline_stats: Baseline statistics for context.

    Example:
        ```python
        results = ScanResults(
            period=DateRange("2025-01-01", "2025-01-24"),
            anomalies=[anomaly1, anomaly2],
            scan_coverage={"events_scanned": 20, "dimensions_scanned": 5},
            baseline_stats={"avg_daily_signups": 450},
        )
        ```
    """

    period: DateRange
    """Date range that was scanned."""

    anomalies: list[Anomaly]
    """List of detected anomalies, ranked by severity * confidence."""

    scan_coverage: dict[str, Any] = field(default_factory=dict)
    """What events/dimensions were analyzed."""

    baseline_stats: dict[str, Any] = field(default_factory=dict)
    """Baseline statistics for context."""


@dataclass
class ContributingFactor:
    """Factor contributing to an anomaly.

    Attributes:
        factor: Description of the factor (e.g., "Mobile Safari users").
        contribution: Percentage of total change explained (0-100).
        evidence: Supporting data or observation.
        confidence: Confidence level in this factor.

    Example:
        ```python
        factor = ContributingFactor(
            factor="Mobile Safari iOS 17 users",
            contribution=78.0,
            evidence="67% drop in this segment vs 5% in others",
            confidence="high",
        )
        ```
    """

    factor: str
    """Description of the factor (e.g., "Mobile Safari users")."""

    contribution: float
    """Percentage of total change explained (0-100)."""

    evidence: str
    """Supporting data or observation."""

    confidence: Literal["high", "medium", "low"]
    """Confidence level in this factor."""


@dataclass
class TimelineEvent:
    """Event in the anomaly timeline.

    Attributes:
        timestamp: When the event occurred.
        description: What happened.
        significance: How significant this event is.

    Example:
        ```python
        event = TimelineEvent(
            timestamp="2025-01-14 23:00",
            description="Deploy detected",
            significance="high",
        )
        ```
    """

    timestamp: str
    """When the event occurred."""

    description: str
    """What happened."""

    significance: Literal["high", "medium", "low"]
    """How significant this event is."""


@dataclass
class Investigation:
    """Complete root cause analysis for an anomaly.

    Contains contributing factors, timeline, segment analysis,
    and supporting evidence.

    Attributes:
        anomaly: The anomaly being investigated.
        root_cause: Primary identified cause (if determined).
        contributing_factors: Factors explaining the anomaly.
        segments_analyzed: Segments that were analyzed.
        timeline: Timeline of relevant events.
        affected_vs_unaffected: Comparison of affected vs unaffected users.
        confidence: Overall confidence in the analysis.
        limitations: What couldn't be determined.
        queries_run: List of queries executed for transparency.
        data_points: Raw data supporting the analysis.

    Example:
        ```python
        investigation = Investigation(
            anomaly=anomaly,
            root_cause="Email validation regex broke on iOS 17 Safari",
            contributing_factors=[factor1, factor2],
            timeline=[TimelineEvent("2025-01-14 23:00", "Deploy detected", "high")],
            confidence="high",
            limitations=["Cannot confirm code change without deploy logs"],
        )
        ```
    """

    anomaly: Anomaly
    """The anomaly being investigated."""

    root_cause: str | None = None
    """Primary identified cause (if determined)."""

    contributing_factors: list[ContributingFactor] = field(default_factory=list)
    """Factors explaining the anomaly."""

    segments_analyzed: list[dict[str, Any]] = field(default_factory=list)
    """Segments that were analyzed."""

    timeline: list[TimelineEvent] = field(default_factory=list)
    """Timeline of relevant events."""

    affected_vs_unaffected: dict[str, Any] = field(default_factory=dict)
    """Comparison of affected vs unaffected users."""

    confidence: Literal["high", "medium", "low"] = "medium"
    """Overall confidence in the analysis."""

    limitations: list[str] = field(default_factory=list)
    """What couldn't be determined."""

    queries_run: list[str] = field(default_factory=list)
    """List of queries executed for transparency."""

    data_points: dict[str, Any] = field(default_factory=dict)
    """Raw data supporting the analysis."""


@dataclass
class Recommendation:
    """Actionable recommendation from analysis.

    Attributes:
        action: What should be done.
        priority: When it should be done.
        impact: Expected impact of the action.
        effort: Estimated effort to implement.
        owner: Suggested owner (if determinable).

    Example:
        ```python
        rec = Recommendation(
            action="Verify iOS 17 Safari compatibility for all form validations",
            priority="immediate",
            impact="Recover 23% of lost signups",
            effort="low",
        )
        ```
    """

    action: str
    """What should be done."""

    priority: Literal["immediate", "soon", "consider"]
    """When it should be done."""

    impact: str
    """Expected impact of the action."""

    effort: Literal["low", "medium", "high"]
    """Estimated effort to implement."""

    owner: str | None = None
    """Suggested owner (if determinable)."""


@dataclass
class ReportSection:
    """Section within a report.

    Attributes:
        title: Section heading.
        content: Section content (markdown).
        data: Optional structured data for the section.

    Example:
        ```python
        section = ReportSection(
            title="Root Cause Analysis",
            content="The primary driver was...",
            data={"drop_percent": 23.0},
        )
        ```
    """

    title: str
    """Section heading."""

    content: str
    """Section content (markdown)."""

    data: dict[str, Any] | None = None
    """Optional structured data for the section."""


@dataclass
class Report:
    """Synthesized findings report.

    Complete report with executive summary, findings,
    recommendations, and formatted output.

    Attributes:
        title: Report title.
        generated_at: Timestamp when report was generated.
        period_analyzed: Date range covered by analysis.
        summary: Executive summary (2-3 sentences).
        key_findings: Bullet-point key findings.
        sections: Detailed report sections.
        recommendations: Prioritized recommendations with effort/impact.
        methodology: Optional methodology description.
        queries_run: Optional list of queries for transparency.
        suggested_follow_ups: Suggested next steps.
        markdown: Full report in markdown format.
        slack_blocks: Optional Slack block formatting.

    Example:
        ```python
        report = Report(
            title="Analytics Brief: Signup Conversion Issue",
            generated_at="2025-01-24T10:30:00Z",
            period_analyzed=DateRange("2025-01-01", "2025-01-24"),
            summary="A deployment on January 14th broke email validation...",
            key_findings=[
                "Signup conversion dropped 23% starting January 15",
                "Root cause: Email validation regex incompatible with iOS 17",
            ],
            recommendations=[rec1, rec2],
            suggested_follow_ups=["Quantify revenue impact"],
        )
        ```
    """

    title: str
    """Report title."""

    generated_at: str
    """Timestamp when report was generated."""

    period_analyzed: DateRange
    """Date range covered by analysis."""

    summary: str
    """Executive summary (2-3 sentences)."""

    key_findings: list[str]
    """Bullet-point key findings."""

    sections: list[ReportSection] = field(default_factory=list)
    """Detailed report sections."""

    recommendations: list[Recommendation] = field(default_factory=list)
    """Prioritized recommendations with effort/impact."""

    methodology: str | None = None
    """Optional methodology description."""

    queries_run: list[str] | None = None
    """Optional list of queries for transparency."""

    suggested_follow_ups: list[str] = field(default_factory=list)
    """Suggested next steps."""

    markdown: str = ""
    """Full report in markdown format."""

    slack_blocks: list[dict[str, Any]] | None = None
    """Optional Slack block formatting."""
